In [1]:
import numpy as np

In [2]:
np.empty([3,4])

array([[1.02631654e-311, 1.02631654e-311, 1.02631654e-311,
        1.26974871e-321],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [3]:
np.empty([3,4])

array([[1.02631654e-311, 1.02631654e-311, 1.02631654e-311,
        1.26974871e-321],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [4]:
np.empty([4,4]) # มันจะมีการสุ่มค่าให้เรา

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        1.11253693e-308]])