In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [6]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
a.ndim

1

In [9]:
b.ndim

2

In [10]:
a.dtype

dtype('int32')

In [11]:
b.dtype

dtype('int32')

In [12]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype="complex")

In [13]:
c

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [14]:
c.dtype

dtype('complex128')

In [15]:
# เป็น 1 มิติ มีข้อมูลอยู่ด้วยกัน 5 ตัว
a.shape

(5,)

In [17]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [18]:
b.shape

(4, 3)

In [19]:
a.size

5

In [20]:
# จะบอกจำนวนสมาชิก
b.size

12

In [21]:
b.dtype

dtype('int32')

In [22]:
b.itemsize

4

In [23]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype="complex")

In [24]:
c.dtype

dtype('complex128')

In [26]:
# จำนวน byte ได้มาจาก 128 / 8 => 8 ตัวหารคือ 8 bit
c.itemsize

16