In [1]:
import numpy as np

In [2]:
a = np.arange(1,11)

In [3]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a[2]

3

In [5]:
# ไม่ได้ระบุค่าอะไร
a[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# ระบุจุดเริ่มต้น
a[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
a[7:]

array([ 8,  9, 10])

In [8]:
# ระบุจุดสุดท้าย
a[:5]

array([1, 2, 3, 4, 5])

In [9]:
# a[start:end]
a[:6]

array([1, 2, 3, 4, 5, 6])

In [10]:
b = np.array([20,10,30,50,40])

In [12]:
b[1:]

array([10, 30, 50, 40])

In [13]:
b[3:]

array([50, 40])

In [14]:
b[:3]

array([20, 10, 30])

In [15]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# แบบระบุช่วง
a[3:7]

array([4, 5, 6, 7])

In [18]:
# เอาตั้งแต่ 3 ถึง 9
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
# กระโดดข้าม ทีละ 2 step
a[2:9:2]

array([3, 5, 7, 9])

In [21]:
b

array([20, 10, 30, 50, 40])

In [24]:
b[1:4]

array([10, 30, 50])

In [25]:
b[1:4:2]

array([10, 50])

In [27]:
c = np.array([10,30,40,50,60,70,75,90])

In [28]:
c

array([10, 30, 40, 50, 60, 70, 75, 90])

In [30]:
c[:]

array([10, 30, 40, 50, 60, 70, 75, 90])

In [31]:
# ให้ข้อมูลขยับไปทีละ 2 step
c[::2]

array([10, 40, 60, 75])

In [32]:
c[::3]

array([10, 50, 75])