In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# x[start,end,step,strat,end,step]
x[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# ระบุจุดเริ่มต้น
x[1:,1:]

array([[5, 6],
       [8, 9]])

In [8]:
x[2:,2:]

array([[9]])

In [9]:
x[2:,1:]

array([[8, 9]])

In [10]:
x[:,2:]

array([[3],
       [6],
       [9]])

In [11]:
x[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])