In [1]:
import numpy as np

In [4]:
x = np.arange(1,10)

In [5]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
index = np.array([1,5,7])

In [7]:
index

array([1, 5, 7])

In [8]:
x[index]

array([2, 6, 8])

In [9]:
# ไว้อ้างอิง index อีกทีนึง

In [10]:
index = np.array([2,4,6,8])

In [11]:
x[index]

array([3, 5, 7, 9])

In [12]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
b[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [16]:
b[[0,2],[2,0]]

array([3, 7])