In [3]:
import numpy as np

In [4]:
a = np.arange(1,5)

In [5]:
a

array([1, 2, 3, 4])

In [6]:
a+2

array([3, 4, 5, 6])

In [7]:
a+10

array([11, 12, 13, 14])

In [8]:
a-5

array([-4, -3, -2, -1])

In [9]:
a*2

array([2, 4, 6, 8])

In [10]:
a*5

array([ 5, 10, 15, 20])

In [11]:
a**2

array([ 1,  4,  9, 16])

In [13]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [14]:
a/3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [19]:
b = np.arange(1,5)

In [20]:
b

array([1, 2, 3, 4])

In [21]:
a+b

array([2, 4, 6, 8])

In [22]:
a.shape

(4,)

In [23]:
b.shape

(4,)

In [24]:
c = np.arange(1,10)

In [25]:
c.shape

(9,)

In [26]:
a+c

ValueError: operands could not be broadcast together with shapes (4,) (9,) 

In [27]:
x = np.array([[1,2,3],[4,5,6]])

In [28]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
y = np.array([[7,8,9],[10,11,12]])

In [30]:
y

array([[ 7,  8,  9],
       [10, 11, 12]])

In [31]:
x+y

array([[ 8, 10, 12],
       [14, 16, 18]])

In [32]:
x-y

array([[-6, -6, -6],
       [-6, -6, -6]])

In [33]:
x*y

array([[ 7, 16, 27],
       [40, 55, 72]])

In [34]:
x**y

array([[          1,         256,       19683],
       [    1048576,    48828125, -2118184960]])

In [35]:
x/y

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [36]:
x%y

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
x+[2]

array([[3, 4, 5],
       [6, 7, 8]])

In [39]:
z = np.array([1,2])

In [40]:
z.shape

(2,)

In [41]:
x.shape

(2, 3)

In [42]:
x+z

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [43]:
z = np.array([1,2,3])

In [44]:
z.shape

(3,)

In [45]:
x+z

array([[2, 4, 6],
       [5, 7, 9]])