In [1]:
import numpy as np

In [4]:
a = np.array([[1,2],[3,4],[5,6]])

In [5]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [7]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
b = a.flatten()

In [9]:
b

array([1, 2, 3, 4, 5, 6])

In [10]:
b[0]=5

In [11]:
b

array([5, 2, 3, 4, 5, 6])

In [12]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
## ถ้า c เปลี่ยน a จะเปลี่ยนไปด้วย
c = a.ravel()

In [14]:
c

array([1, 2, 3, 4, 5, 6])

In [15]:
c[0] = 5

In [16]:
c

array([5, 2, 3, 4, 5, 6])

In [17]:
a

array([[5, 2],
       [3, 4],
       [5, 6]])