In [1]:
import numpy as np

In [2]:

a = np.array([10,5,4,6,99,100,50,30])

In [3]:
a

array([ 10,   5,   4,   6,  99, 100,  50,  30])

In [4]:
# ผลรวม
a.sum()

304

In [5]:
# ผลคูณ
a.prod()

640130816

In [6]:
a.mean()

38.0

In [7]:
a.max()

100

In [8]:
a.min()

4

In [9]:
# index ที่ค่าสูงสุด
a.argmax()

5

In [10]:
b = np.array([[10,20,30],[40,50,90],[80,100,5]])

In [12]:
b

array([[ 10,  20,  30],
       [ 40,  50,  90],
       [ 80, 100,   5]])

In [13]:
# หาค่าต่ำสุดในแนวนอน
np.min(b,axis=1)

array([10, 40,  5])

In [14]:
# หาค่าต่ำสุดในแนวตั้ง
np.min(b,axis=0)

array([10, 20,  5])

In [15]:
np.max(b,axis=1)

array([ 30,  90, 100])

In [16]:
np.max(b,axis=0)

array([ 80, 100,  90])