In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],[3,4]])

In [3]:
a

array([[1, 2],
       [3, 4]])

In [4]:
b = np.array([[11,12],[13,14]])

In [5]:
b

array([[11, 12],
       [13, 14]])

In [6]:
c = a.dot(b)

In [7]:
c

array([[37, 40],
       [85, 92]])