In [1]:
import numpy as np

In [2]:
a = np.array([3,4,2,6])

In [3]:
a

array([3, 4, 2, 6])

In [4]:
b = np.array([8,6,5,10])

In [5]:
b

array([ 8,  6,  5, 10])

In [6]:
np.concatenate((a,b))

array([ 3,  4,  2,  6,  8,  6,  5, 10])

In [7]:
c = np.concatenate((a,b))

In [8]:
c

array([ 3,  4,  2,  6,  8,  6,  5, 10])

In [9]:
np.append(a,100)

array([  3,   4,   2,   6, 100])

In [10]:
np.append(a,500)

array([  3,   4,   2,   6, 500])

In [11]:
a = np.append(a,500)

In [12]:
a

array([  3,   4,   2,   6, 500])

In [13]:
a = np.append(a,1000)

In [14]:
a

array([   3,    4,    2,    6,  500, 1000])

In [15]:
b = np.array([[1,2],[3,4]])

In [17]:
b

array([[1, 2],
       [3, 4]])

In [23]:
b = np.append(b,[[10],[20]],axis=1)

In [24]:
b

array([[ 1,  2, 10],
       [ 3,  4, 20]])