In [5]:
# import numpy
import numpy as np

In [6]:
# create array 0 มิติ
a = np.array(1)

In [7]:
a

array(1)

In [8]:
# create array 2 มิติ
b = np.array(2)

In [9]:
b

array(2)

In [10]:
# check มิติของ array
a.ndim

0

In [11]:
b.ndim

0

In [12]:
# create array 1 มิติ
c = np.array([1,2,3])

In [13]:
c.ndim

1

In [14]:
li = [1,2,3,4]

In [15]:
d = np.array(li)

In [16]:
d

array([1, 2, 3, 4])

In [17]:
d.ndim

1

In [18]:
tu = (1,2,3,4,5,6,7,8,9,10)

In [19]:
e = np.array(tu)

In [20]:
e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
e.ndim

1

In [22]:
f = np.array((1,2,3,4))

In [23]:
f

array([1, 2, 3, 4])