In [1]:
import numpy as np

In [2]:
a = np.arange(1,11)

In [3]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.delete(a,2)

array([ 1,  2,  4,  5,  6,  7,  8,  9, 10])

In [5]:
a = np.arange(1,13)

In [6]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
a = np.arange(1,13).reshape(4,3)

In [8]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
np.delete(a,2,axis=1)

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [10]:
np.delete(a,2,axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [11]:
np.delete(a,0,axis=0)

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
np.delete(a,0,axis=1)

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])