In [5]:
import numpy as np

In [6]:
a = np.array([1,2,3,4,5])

In [7]:
a[2] = 100

In [8]:
a

array([  1,   2, 100,   4,   5])

In [10]:
a = np.array([[1,2],[3,4],[5,6]])

In [11]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
# การเข้าถึง array จะเอาเลข 4
# a[row][col] => row ที่ 1 , col ที่ 1
a[1][1]

4

In [14]:
# เอาเลข 5 มาใช้งาน
a[2][0]

5

In [15]:
a[0][1]

2

In [16]:
# เปลี่ยนเลข 2 เป็น 500
a[0][1] = 500

In [17]:
a

array([[  1, 500],
       [  3,   4],
       [  5,   6]])

In [18]:
# การเพิมจำนวน column
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# อยากเข้าถึงเลข 8
b[2][1]

8

In [21]:
# เอาเลข 5 มาใช้โดยเข้าถึง index แบบตำแหน่งติดลบ
b[-2][-2]

5