In [13]:
import numpy as np

In [14]:
a = np.array([[[1,2,3],[4,5,6]]])

In [15]:
a

array([[[1, 2, 3],
        [4, 5, 6]]])

In [16]:
# วิธีการเข้าถึงสมาชิก ใน สามมิติ
# a[dept][row][col]
# ชั้นท่ี่ 0
a[0][1][1]

5

In [17]:
# อยากได้เลข 3
a[0][0][2]

3

In [18]:
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [19]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
b[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [21]:
b[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# อยากเข้าถึง ข้อมูลสมาชิก
# อยากได้เลข 8
b[1][0][1]

8

In [23]:
# อยากได้เลข 3
b[0][0][2]

3