In [12]:
print("Data Type")

Data Type


In [13]:
# 1 Integer
# 2 Float
# 3 String
# 4 Boolean
# 5 Complex
# 6 Object

In [14]:
import numpy as np

In [15]:
a = np.array([1,2,3,4,5])

In [16]:
a

array([1, 2, 3, 4, 5])

In [17]:
a.dtype

dtype('int32')

In [18]:
a = np.array([1,2,3,4,5],dtype="int")

In [19]:
a.dtype

dtype('int32')

In [20]:
a = np.array([1,2,3,4,5],dtype="float")

In [21]:
a

array([1., 2., 3., 4., 5.])

In [22]:
a.dtype

dtype('float64')

In [23]:
a = np.array([1,2,3,4,5],dtype="complex")

In [24]:
a

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [25]:
a.dtype

dtype('complex128')

In [27]:
b = np.array([[1,2,3],[3,4,5]],dtype="float")

In [28]:
b

array([[1., 2., 3.],
       [3., 4., 5.]])