In [3]:
# array 2 มิติ = Matrix
# Square Matrix มิติแถวหลักเท่ากัน
# Zero Matrix สมาชิกทุกตัวเป็น 0
# Identity Matrix เส้นแทยงมุมเป็น 1 นอกนั้นเป็น 0

In [4]:
import numpy as np

In [5]:
a = np.zeros(5)

In [6]:
a

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
# สร้างแถวเดียว
np.zeros(5,dtype="int")

array([0, 0, 0, 0, 0])

In [10]:
# สร้างสองแถว สองคอลัมน์
np.zeros((2,2),dtype="int")

array([[0, 0],
       [0, 0]])

In [11]:
# สร้างสามแถว สี่คอลัมน์
np.zeros([3,4],dtype="int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
np.zeros([3,3],dtype="int")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])